/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pinballapi_free: (a: number, b: number) => void;
export const pinballapi_ball_dying: (a: number) => number;
export const pinballapi_ball_dying_timer: (a: number) => number;
export const pinballapi_ball_present: (a: number) => number;
export const pinballapi_ball_save_fraction: (a: number) => number;
export const pinballapi_ball_waiting: (a: number) => number;
export const pinballapi_ball_x: (a: number) => number;
export const pinballapi_ball_y: (a: number) => number;
export const pinballapi_balls_left: (a: number) => number;
export const pinballapi_bumper_count: (a: number) => number;
export const pinballapi_bumper_flash: (a: number, b: number) => number;
export const pinballapi_combo_fraction: (a: number) => number;
export const pinballapi_combo_multiplier: (a: number) => number;
export const pinballapi_flipper_angle: (a: number, b: number) => number;
export const pinballapi_flipper_count: (a: number) => number;
export const pinballapi_flipper_is_moving_up: (a: number, b: number) => number;
export const pinballapi_high_score: (a: number) => number;
export const pinballapi_is_ball_save_active: (a: number) => number;
export const pinballapi_kickback_count: (a: number) => number;
export const pinballapi_kickback_flash: (a: number, b: number) => number;
export const pinballapi_launch_power: (a: number) => number;
export const pinballapi_new: (a: number) => number;
export const pinballapi_nudge: (a: number, b: number, c: number) => [number, number];
export const pinballapi_over: (a: number) => number;
export const pinballapi_reset: (a: number) => void;
export const pinballapi_score: (a: number) => number;
export const pinballapi_set_launch_power: (a: number, b: number) => void;
export const pinballapi_shake_x: (a: number) => number;
export const pinballapi_shake_y: (a: number) => number;
export const pinballapi_slingshot_count: (a: number) => number;
export const pinballapi_slingshot_flash: (a: number, b: number) => number;
export const pinballapi_step: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const pinballapi_tilted: (a: number) => number;
export const pinballapi_trigger_launch: (a: number, b: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
